### ISSUE TITLE
Possible improvement to argument routes

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Compass#11]
I've been playing around with the idea to change the syntax for arguments in the routes; instead of using `{}`, you could use the dollar sign as a prefix delimiter to determine if it's a argument or not.

So this would mean that the route would look like;
`profile:$user` instead of `profile:{user}`.

What do you think?

**Comment by vadymmarkov** [comment]
@zenangst Don't like `$` sign, it's post-php syndrome :smile: I'm Ok with `profile:{user}` or `profile:<user>`

**Comment by zenangst** [comment]
@vadymmarkov :grin:

The thing is, I kinda only want one delimiter, but I guess its fine as it is :sunglasses:

**Comment by zenangst** [comment]
@RamonGilabert what do you think?

**Comment by RamonGilabert** [comment]
One of the ways in python is: `% (user, age)`, another way (inside a string) is `%(user)s %(age)d`. What about:

`profile: user, age, stuff`.

Use the space as a separator?

**Comment by vadymmarkov** [comment]
@RamonGilabert :snake: 

Then `profile:#{user}`, Ruby way.

**Comment by zenangst** [comment]
@RamonGilabert @vadymmarkov 
![giphy-71](https://cloud.githubusercontent.com/assets/57446/11332921/11739ec6-91ca-11e5-8dd3-c15b4bd849e6.gif)

**Comment by zenangst** [comment]
Just gonna close this :grin:
