### ISSUE TITLE
Return clean argument keys

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Compass#12]
Personally I think it looks kinda weird that the delimiter is included in the arguments dictionary that you get when you resolve arguments. I'd like to strip it out from the key entirely.

**Before**

``` swift
Compass.parse(url) { route, arguments in
  XCTAssertEqual("login:{username}:{password}", route)
  XCTAssertEqual(arguments["{username}"], "JohnHyperseed")
  XCTAssertEqual(arguments["{password}"], "secret")
}
```

**After**

``` swift
Compass.parse(url) { route, arguments in
  XCTAssertEqual("login:{username}:{password}", route)
  XCTAssertEqual(arguments["username"], "JohnHyperseed")
  XCTAssertEqual(arguments["password"], "secret")
}
```

**Comment by vadymmarkov** [comment]
@zenangst Yeah, totally agree. I was thinking about that too, but forgot to tell you :smile:

**Comment by zenangst** [comment]
@vadymmarkov look, a wild pull request appeared :sunglasses:
