### ISSUE TITLE
Conversion to Swift 3

### ISSUE THREAD

**Issue by garrefa** [hyperoslo/Compass#36]
Guys, any plan to convert this lib to swift 3? Should i submit a PR?

**Comment by zenangst** [comment]
@garrefa hey man! yeah feel free to make a pull request, I made a branch that you can make a PR towards. `swift-3`.

**Comment by zenangst** [comment]
Hey @garrefa, great news, `3.x.x` is now Swift 3. Closing this issue now ✋

**Comment by zenangst** [comment]
Oh, totally my bad. It is on `master` not released. Gonna be release soon, and I don't mean [Blizzard soon](http://wowwiki.wikia.com/wiki/Soon).

**Comment by vadymmarkov** [comment]
v4.0.0 is released 🎉
