### ISSUE TITLE
Support Xcode 8 + Swift 2.3

### ISSUE THREAD

**Issue by garrefa** [hyperoslo/Compass#37]
Hi guys, ill submit a conversion to swift 2.3 too, can you open another branch?
I think this should be version 3.1.0 and the swift 3 should be 4.0.0. What do you guys think?
Thanks

**Comment by zenangst** [comment]
Hey @garrefa, I've pushed a new branch called `swift-2.3`, cheers! 🍻

**Comment by garrefa** [comment]
PR sent :) I'll convert Sugar and Hex to 2.3 first, than 3.0

**Comment by zenangst** [comment]
@garrefa any work being done on this? Or should we just close the issue? I don't think that Apple will keep Swift 2.3 around for long. I remember reading something about that in the release notes for Xcode.

**Comment by zenangst** [comment]
I'm just gonna go head and close this one because of lacking activity.
