### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by esetnik** [hyperoslo/Compass#44]
It looks like the `Compass` module has the same name as the `Compass` struct. This causes a problem if the user target also has defined types like `Location` and `Router` because they cannot be specified like `Compass.Location` and `Compass.Router`. I think to fix this it would be necessary to rename the module something like `CompassKit`.

https://twitter.com/geeklu/status/674153362200256512

**Comment by onmyway133** [comment]
@esetnik that 's right. Maybe the `Compass` struct needs to be renamed to workaround this Swift restriction

**Comment by onmyway133** [comment]
ping @hyperoslo/ios

**Comment by vadymmarkov** [comment]
Yes, I agree. We just need a good name 😄

**Comment by onmyway133** [comment]
Maybe

- Scout
- Navigator
- Journey
- Square
- Terminal
- Jernbanetorget

**Comment by vadymmarkov** [comment]
Navigator should work I think.

**Comment by zenangst** [comment]
My vote is on `Navigator`.

**Comment by onmyway133** [comment]
@esetnik Hi, FYI https://github.com/hyperoslo/Compass/releases/tag/5.0.0 😉
